In [100]:
import pandas as pd
import json
import torch

In [99]:
print(torch.__version__)
print(torch.cuda.is_available())

1.9.0+cu102
True

In [111]:
eventft = pd.read_csv("userft_new.csv")

In [113]:
for i in eventft.columns[2:]:
    if(eventft[i].max()!=eventft[i].min()):
        print(i)

age_level
user_level
if_inviter_participate_x
if_voter_participate_x
inviter_num
voter_num
if_inviter_participate_rate
if_voter_participate_rate
inviter_num_target
voter_num_target
if_inviter_participate_target
if_voter_participate_target
if_inviter_participate_rate_target
if_voter_participate_rate_target
-1_x
1_x
2_x
3_x
4_x
5_x
6_x
7_x
8_x
9_x
10_x
-1_y
1_y
2_y
3_y
4_y
5_y
6_y
7_y
8_y
202112_x
202201_x
202202_x
202203_x
202204_x
202205_x
202206_x
202207_x
202208_x
202209_x
202210_x
202211_x
202212_x
user_level_voter
age_level_voter
-1_x.1
1_x.1
2_x.1
3_x.1
4_x.1
5_x.1
6_x.1
7_x.1
8_x.1
9_y
10_y
-1_y.1
1_y.1
2_y.1
3_y.1
4_y.1
5_y.1
6_y.1
7_y.1
8_y.1
202112_y
202201_y
202202_y
202203_y
202204_y
202205_y
202206_y
202207_y
202208_y
202209_y
202210_y
202211_y
202212_y
user_level_inviter
age_level_inviter

In [87]:
userft = pd.read_csv("userft.csv")
userft.head()

,user_id,gender_id,age_level,user_level,if_inviter_participate_x,if_voter_participate_x,inviter_num,voter_num,if_inviter_participate_rate,if_voter_participate_rate,inviter_num_target,voter_num_target,if_inviter_participate_target,if_voter_participate_target,if_inviter_participate_rate_target,if_voter_participate_rate_target
0,00005b3845d3f3bc9f1ee2f48fab25d2,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0000c288f15342731714c83a76ae7794,1,4,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0000ff11090eeecaf896e0fbfa978f89,0,6,8,0.0,1.0,1.0,10.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0
3,000100b8c1a2b5c99aa120ea0bfcecd5,0,4,4,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000111daac5bf38e71c308f8d30328c3,0,5,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
userft["user_id"].nunique()

299889

In [12]:
source_train = pd.read_json("source_event_preliminary_train_info.json")

In [14]:
target_train = pd.read_json("target_event_preliminary_train_info.json")

In [15]:
target_train

,inviter_id,event_id,voter_id,if_inviter_participate,if_voter_participate,ds
0,0027ce5ceb8a0486431ac71bd09d97b0,74eacfb6b4e11fe58d0f610f167aac67,053f750049cafcad7a039907c08da458,0,0,20221112
1,10b7696aa18c8e5d4d15271ff628eebb,74eacfb6b4e11fe58d0f610f167aac67,844e8b329948eb119f95885b23c868b5,0,0,20221112
2,0a8325ca835dec9e081b397892f9bd87,811ba9ddbf8ba61af81f99bffcc90b47,ce913eb2f5a65d5ecb6ecb362983a967,0,0,20221112
3,15fe6789107f4eeeed87aa4d6e89ebcb,3f55e8066c467d14885feb3a7c8d338b,f64f3d5f2b4f2fb54a71ec7540a2ed9c,0,0,20221112
4,037e5750a02b81830e56a583a8b9edc4,e47ab9e446bfb932620bfbb799c9b1bb,260053464256510c224c843cec585295,0,0,20221112
...,...,...,...,...,...,...
20094,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,d3c0cd2c4b58f8aec8b8a66c5741bf47,0,0,20221224
20095,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,e172c13e2fc6a17a38d1f67757431ef9,0,0,20221224
20096,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,e6491b2da99039ecd0e31bc0c26bf6fa,0,0,20221224
20097,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,edfaf01480597ba6a926508ee7a8d142,0,0,20221224
20098,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,fbddb39a10bff8b8b72ec74732cb7ada,0,0,20221224

In [16]:
all_train = pd.concat([source_train,target_train],ignore_index = True)

In [18]:
event = pd.read_json("event_info.json")

In [20]:
event.head()

                           event_id                   parent_event_id
0  3f55e8066c467d14885feb3a7c8d338b  9acf9c6f117a4c2d02de30294ec29da9
1  4a6758d5ea4e812bd23c82c5d92c87ae  53b4b807fb3570b13d95509de71080be
2  704d5c7355ae1b3331574ed19d3fbe59  704d5c7355ae1b3331574ed19d3fbe59
3  e8e0cf361ff136cdaf9c6a38c45e5ac5  e1acd6855878d06358834b9138ff022e
4  a03082d84eb9f8120805da377f84629c  0acc3f66b631cdfa14ec5e3c163def03

In [22]:
all_train["event_id"].nunique()

48

In [32]:
all_train.head()

,inviter_id,event_id,voter_id,if_inviter_participate,if_voter_participate,ds
0,08d5cdc89d8c2452956955ea9174c392,58b056bd92cfa0b0bca4cd70af9377c1,e38338c104e99a9f5359114e61cbdeaf,1,0,20211227
1,0f9806475cd29139b59edbb685d0c2a9,0acc3f66b631cdfa14ec5e3c163def03,4d88bbcb618d63e693082c4c88cf0439,0,0,20211227
2,0ad3c7c908c44359e4e16cfa070016fb,58b056bd92cfa0b0bca4cd70af9377c1,cdd154d18d56dc4fc402636d71a1f821,0,0,20211227
3,0d5cc5a8daf7ba3bd15bd498a7e6698e,b7771665663941f898d1fdd6b01889a9,debf9cc89d42316250120f40b39d3b93,0,0,20211227
4,0dde51b3f57d891753ea5c0095af4b5f,e83fc587661220aebe5e83915e0d5e15,a8a9ee887a5b6373b288d59ab9a78ec8,0,0,20211227

In [33]:
user = pd.read_json("user_info.json")

In [34]:
user.head()

                            user_id  gender_id  age_level  user_level
0  00005b3845d3f3bc9f1ee2f48fab25d2          1          1           1
1  0000c288f15342731714c83a76ae7794          1          4           1
2  0000ff11090eeecaf896e0fbfa978f89          0          6           8
3  000100b8c1a2b5c99aa120ea0bfcecd5          0          4           4
4  000111daac5bf38e71c308f8d30328c3          0          5           9

In [45]:
user_eventft = all_train.merge(user,how="left",left_on="inviter_id",right_on="user_id")

In [46]:
user_eventft = user_eventft.merge(user,how="left",left_on="voter_id",right_on="user_id",suffixes=["_inviter","_voter"])

In [49]:
user_eventft =user_eventft.drop(["user_id_inviter","user_id_voter"],axis=1)

In [50]:
user_eventft

,inviter_id,event_id,voter_id,if_inviter_participate,if_voter_participate,ds,gender_id_inviter,age_level_inviter,user_level_inviter,gender_id_voter,age_level_voter,user_level_voter
0,08d5cdc89d8c2452956955ea9174c392,58b056bd92cfa0b0bca4cd70af9377c1,e38338c104e99a9f5359114e61cbdeaf,1,0,20211227,0,5,10,0,4,5
1,0f9806475cd29139b59edbb685d0c2a9,0acc3f66b631cdfa14ec5e3c163def03,4d88bbcb618d63e693082c4c88cf0439,0,0,20211227,0,6,7,0,4,6
2,0ad3c7c908c44359e4e16cfa070016fb,58b056bd92cfa0b0bca4cd70af9377c1,cdd154d18d56dc4fc402636d71a1f821,0,0,20211227,1,4,10,0,2,2
3,0d5cc5a8daf7ba3bd15bd498a7e6698e,b7771665663941f898d1fdd6b01889a9,debf9cc89d42316250120f40b39d3b93,0,0,20211227,0,3,7,0,3,5
4,0dde51b3f57d891753ea5c0095af4b5f,e83fc587661220aebe5e83915e0d5e15,a8a9ee887a5b6373b288d59ab9a78ec8,0,0,20211227,0,2,3,0,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1068522,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,d3c0cd2c4b58f8aec8b8a66c5741bf47,0,0,20221224,0,7,8,0,2,1
1068523,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,e172c13e2fc6a17a38d1f67757431ef9,0,0,20221224,0,7,8,-1,-1,1
1068524,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,e6491b2da99039ecd0e31bc0c26bf6fa,0,0,20221224,0,7,8,1,6,4
1068525,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,edfaf01480597ba6a926508ee7a8d142,0,0,20221224,0,7,8,1,3,3
1068526,f728ef815e38ce75562fe2655fd16f70,3f55e8066c467d14885feb3a7c8d338b,fbddb39a10bff8b8b72ec74732cb7ada,0,0,20221224,0,7,8,1,1,2

In [66]:
user_eventft["month"] = user_eventft["ds"]/100
user_eventft["month"] = user_eventft["month"].astype("int")

In [96]:
user_eventft["month"].value_counts()

202211    145374
202210    133252
202212    103348
202209     99282
202208     93401
202207     82918
202206     77283
202205     76890
202203     72607
202204     65540
202201     59259
202202     46135
202112     13238
Name: month, dtype: int64

In [72]:
a = user_eventft.groupby(["event_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
b = user_eventft.groupby(["event_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
c = user_eventft.groupby(["event_id","user_level_voter"])["user_level_voter"].count().unstack().reset_index()
d = user_eventft.groupby(["event_id","age_level_voter"])["age_level_voter"].count().unstack().reset_index()
e = user_eventft.groupby(["event_id","month"])["month"].count().unstack().reset_index()
eventft = eventft.merge(a,on="event_id",how="left")
eventft = eventft.merge(b,on="event_id",how="left")
eventft = eventft.merge(c,on="event_id",how="left")
eventft = eventft.merge(d,on="event_id",how="left")
eventft = eventft.merge(e,on="event_id",how="left")

In [77]:
a = user_eventft[user_eventft["if_inviter_participate"]==1].groupby(["event_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
b = user_eventft[user_eventft["if_inviter_participate"]==1].groupby(["event_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
c = user_eventft[user_eventft["if_inviter_participate"]==1].groupby(["event_id","user_level_voter"])["user_level_voter"].count().unstack().reset_index()
d = user_eventft[user_eventft["if_inviter_participate"]==1].groupby(["event_id","age_level_voter"])["age_level_voter"].count().unstack().reset_index()
e = user_eventft[user_eventft["if_inviter_participate"]==1].groupby(["event_id","month"])["month"].count().unstack().reset_index()
eventft = eventft.merge(a,on="event_id",how="left")
eventft = eventft.merge(b,on="event_id",how="left")
eventft = eventft.merge(c,on="event_id",how="left")
eventft = eventft.merge(d,on="event_id",how="left")
eventft = eventft.merge(e,on="event_id",how="left")

In [79]:
a = user_eventft[user_eventft["if_voter_participate"]==1].groupby(["event_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
b = user_eventft[user_eventft["if_voter_participate"]==1].groupby(["event_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
c = user_eventft[user_eventft["if_voter_participate"]==1].groupby(["event_id","user_level_voter"])["user_level_voter"].count().unstack().reset_index()
d = user_eventft[user_eventft["if_voter_participate"]==1].groupby(["event_id","age_level_voter"])["age_level_voter"].count().unstack().reset_index()
e = user_eventft[user_eventft["if_voter_participate"]==1].groupby(["event_id","month"])["month"].count().unstack().reset_index()
eventft = eventft.merge(a,on="event_id",how="left")
eventft = eventft.merge(b,on="event_id",how="left")
eventft = eventft.merge(c,on="event_id",how="left")
eventft = eventft.merge(d,on="event_id",how="left")
eventft = eventft.merge(e,on="event_id",how="left")

In [82]:
eventft.head()

,event_id,parent_event_id,age_level_x,user_level_x,age_level_y,user_level_y,man_x,woman_x,man_y,woman_y,...,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212
0,3f55e8066c467d14885feb3a7c8d338b,9acf9c6f117a4c2d02de30294ec29da9,3.200793,5.342580,3.200793,5.342580,397.0,4145.0,7.0,4535.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,465.0,529.0
1,4a6758d5ea4e812bd23c82c5d92c87ae,53b4b807fb3570b13d95509de71080be,3.004972,5.791193,3.004972,5.791193,111.0,1297.0,99.0,1309.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.0,253.0
2,704d5c7355ae1b3331574ed19d3fbe59,704d5c7355ae1b3331574ed19d3fbe59,2.669343,5.812271,2.669343,5.812271,5914.0,24353.0,3175.0,27092.0,...,686.0,629.0,637.0,533.0,749.0,1120.0,1363.0,1835.0,1822.0,1128.0
3,e8e0cf361ff136cdaf9c6a38c45e5ac5,e1acd6855878d06358834b9138ff022e,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a03082d84eb9f8120805da377f84629c,0acc3f66b631cdfa14ec5e3c163def03,3.013479,6.227260,3.013479,6.227260,3953.0,38483.0,1816.0,40620.0,...,939.0,504.0,685.0,637.0,690.0,716.0,850.0,1650.0,1367.0,733.0

In [81]:
eventft = eventft.fillna(0)

In [83]:
eventft.to_csv("eventft_new.csv",index = False)

In [88]:
# a = user_eventft.groupby(["inviter_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
# b = user_eventft.groupby(["inviter_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
c = user_eventft.groupby(["inviter_id","user_level_voter"])["user_level_voter"].count().unstack().reset_index()
d = user_eventft.groupby(["inviter_id","age_level_voter"])["age_level_voter"].count().unstack().reset_index()
e = user_eventft.groupby(["inviter_id","month"])["month"].count().unstack().reset_index()
f = user_eventft.groupby(["inviter_id"])["user_level_voter"].mean().reset_index()
g = user_eventft.groupby(["inviter_id"])["age_level_voter"].mean().reset_index()

# eventft = eventft.merge(a,on="event_id",how="left")
# eventft = eventft.merge(b,on="event_id",how="left")
userft = userft.merge(c,left_on="user_id",right_on="inviter_id",how="left").drop("inviter_id",axis=1)
userft = userft.merge(d,left_on="user_id",right_on="inviter_id",how="left").drop("inviter_id",axis=1)
userft = userft.merge(e,left_on="user_id",right_on="inviter_id",how="left").drop("inviter_id",axis=1)
userft = userft.merge(f,left_on="user_id",right_on="inviter_id",how="left").drop("inviter_id",axis=1)
userft = userft.merge(g,left_on="user_id",right_on="inviter_id",how="left").drop("inviter_id",axis=1)

In [89]:
# a = user_eventft.groupby(["inviter_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
# b = user_eventft.groupby(["inviter_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
c = user_eventft.groupby(["voter_id","user_level_inviter"])["user_level_inviter"].count().unstack().reset_index()
d = user_eventft.groupby(["voter_id","age_level_inviter"])["age_level_inviter"].count().unstack().reset_index()
e = user_eventft.groupby(["voter_id","month"])["month"].count().unstack().reset_index()
f = user_eventft.groupby(["voter_id"])["user_level_inviter"].mean().reset_index()
g = user_eventft.groupby(["voter_id"])["age_level_inviter"].mean().reset_index()

# eventft = eventft.merge(a,on="event_id",how="left")
# eventft = eventft.merge(b,on="event_id",how="left")
userft = userft.merge(c,left_on="user_id",right_on="voter_id",how="left").drop("voter_id",axis=1)
userft = userft.merge(d,left_on="user_id",right_on="voter_id",how="left").drop("voter_id",axis=1)
userft = userft.merge(e,left_on="user_id",right_on="voter_id",how="left").drop("voter_id",axis=1)
userft = userft.merge(f,left_on="user_id",right_on="voter_id",how="left").drop("voter_id",axis=1)
userft = userft.merge(g,left_on="user_id",right_on="voter_id",how="left").drop("voter_id",axis=1)

In [91]:
userft = userft.fillna(0)

In [92]:
userft.to_csv("userft.csv",index=False)

,user_id,gender_id,age_level,user_level,if_inviter_participate_x,if_voter_participate_x,inviter_num,voter_num,if_inviter_participate_rate,if_voter_participate_rate,...,202205_y,202206_y,202207_y,202208_y,202209_y,202210_y,202211_y,202212_y,user_level_inviter,age_level_inviter
0,00005b3845d3f3bc9f1ee2f48fab25d2,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,6.0,3.0
1,0000c288f15342731714c83a76ae7794,1,4,1,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.5
2,0000ff11090eeecaf896e0fbfa978f89,0,6,8,0.0,1.0,1.0,10.0,0.0,0.1,...,1.0,2.0,1.0,0.0,0.0,1.0,1.0,1.0,7.9,5.6
3,000100b8c1a2b5c99aa120ea0bfcecd5,0,4,4,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000111daac5bf38e71c308f8d30328c3,0,5,9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299884,fffef0bf3a0cd81256d91d5add410f3a,1,6,9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299885,fffeff284546f903c3119e1c00dae59d,-1,-1,1,0.0,0.0,34.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299886,ffff629a3bdcf506b15775515f4f0cb9,0,2,3,0.0,0.0,2.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,2.0
299887,ffffbdcedba29056ffed3b9ce20feb99,0,6,8,0.0,1.0,0.0,5.0,0.0,0.2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.4,3.4
299888,ffffe652c6dd5618a1ca05e39ed5f184,0,3,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
userft.to_csv("userft_new.csv",index=False)